# Generated by Django 5.2.7 on 2025-11-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='name',
        ),
        migrations.RemoveField(
            model_name='node',
            name='description',
        ),
        migrations.AddField(
            model_name='graph',
            name='text',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='node',
            name='entity',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='node',
            name='text',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='graph',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
