# Generated by Django 5.2.7 on 2025-11-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_graph_name_remove_node_description_graph_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='node',
            name='name',
        ),
        migrations.AlterField(
            model_name='node',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
